In [1]:
import pandas as pd
import numpy as np  

In [2]:
from sklearn.datasets import make_classification

C:\Users\vikra\anaconda3\envs\myenv\lib\site-packages\sklearn\feature_extraction\text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, defaultdict


In [3]:
dataset = load_iris()

X = dataset.data
y = dataset.target

mu = np.mean(X, 0)
sigma = np.std(X, 0)
X = (X - mu ) / sigma

X_train, X_test, y_train, y_test = train_test_split(\
                X, y, test_size=0.3, random_state=45)

NameError: name 'load_iris' is not defined

In [15]:
def euclidian_distance(a,b):
    return np.sqrt(np.sum((a-b)**2,axis=1))

In [10]:
# enumerate function
l1 = ["eat","sleep","repeat"]
s1 = "geek"
 
# creating enumerate objects
obj1 = enumerate(l1)
obj2 = enumerate(s1)
 
print ("Return type:",type(obj1))
print (list(enumerate(l1)))
 
# changing start index to 2 from 0
print (list(enumerate(s1,2)))

Return type: <class 'enumerate'>
[(0, 'eat'), (1, 'sleep'), (2, 'repeat')]
[(2, 'g'), (3, 'e'), (4, 'e'), (5, 'k')]


In [11]:
for r in l1:
        enum_neigh=enumerate(r)
        print(enum_neigh)

In [8]:
enum_neigh

In [33]:
mylist = [[7, 8], [1, 2, 3], [2, 5, 6]]
# list(map(lambda x: x[1], mylist)) returns [8, 2 ,5]

mylistSort = sorted(mylist, key = lambda x: x[1])
# will sort the nested list based on the result of the lambda function 
mylistSort

[[1, 2, 3], [2, 5, 6], [7, 8]]

hi

In [36]:
def knn(X_test, return_distance=False):
    n_neighbors = 5
    dist=[]
    neigh_ind=[]
    point_dist=[euclidian_distance(x_test,X_train) for x_test in X_test]
    
    for row in point_dist:
        enum_neigh=enumerate(row)   #[(0, 'dis1'), (1, 'dis2'), (2, 'dis3')] tuple
        #print(enum_neigh)
        sorted_neigh = sorted(enum_neigh, key=lambda x: x[1])[:n_neighbors] # will sort the nested list based on the result of the lambda function i.e dis
        #print(sorted_neigh)
        ind_list = [tup[0] for tup in sorted_neigh]
        dist_list = [tup[1] for tup in sorted_neigh]
    
        dist.append(dist_list)
        neigh_ind.append(ind_list)
        
    if return_distance:
        return np.array(dist), np.array(neigh_ind)
        
    return np.array(neigh_ind)


In [39]:
knn(X_test, return_distance=False)# 5 neigh of every x_test

array([[ 87,  55,  20,  24,  70],
       [ 87,  22,   0,  24,  55],
       [ 49,  46,  78,  66,  77],
       [ 13,  11,  19,  71,  88],
       [  4,  30,  88,  11,   5],
       [ 10,  92,   0,  42,   8],
       [ 91,  71,   5,  88,  13],
       [ 26,  36,  49,  78,  46],
       [ 85,   1,  32,  59,  62],
       [ 40,  98,  18,  69,  77],
       [ 20,  55,  24,  87,  31],
       [ 46,  77,  49,  98, 103],
       [ 99,  59,  32,  37,  85],
       [ 63,   7,  54,  53,  85],
       [ 62,  64,  85,  32,  28],
       [ 67,   4,  30,  19,  11],
       [ 18,  69,  77,  54,  98],
       [ 99,  32,  85,  37,  52],
       [ 87,  24,  55,  20,  70],
       [100,  15,   2,  59,  95],
       [  6,  43, 101,  76,  44],
       [ 84,  48,  76,  16,  86],
       [ 86,  68,  90,  35, 103],
       [ 84,  79,  96,  65,  66],
       [ 87,  55,   0,   8,  24],
       [ 77,  54,  69,  46,  18],
       [ 39,  17,  12,  75,  14],
       [ 43,  47, 101,  44,  12],
       [  8,  92,   0,  10,  33],
       [ 64,  

In [41]:
# 1D array with +ve integers
array1 = [1, 6, 1, 1, 1, 2, 2]
bin = np.bincount(array1)
print("Bincount output  : \n ", bin)
print("size of bin : ", len(bin), "\n")

Bincount output  : 
  [0 4 2 0 0 0 1]
size of bin :  7 



In [42]:
array1 = [1, 6, 1, 1, 1, 2, 2]
np.argmax(array1)

1

numpy.argmax(numpy.bincount(dlabel)) returns the most common value found in dlabel.

To break it down, np.bincount() will return the count of each value in an array of non-negative integers and return an array with the count at the appropriate index (Python arrays are indexed from 0). For example:

>>> np.bincount([1,2,3,2,4,1,1,0])
array([1, 3, 2, 1, 1], dtype=int32)
(So 0 appears once, 1 appears three times, ...)

np.argmax() returns the index of the (first) maximum value in an array.

>>> np.argmax(np.bincount([1,2,3,2,4,1,1,0]))
1
So combining the two functions, we can find that 1 appears most often in [1,2,3,2,4,1,1,0] (it appears 3 times).

In [ ]:
def predict(X_test, weights='uniform'):
        
        class_num = 3
        
        if weights=='uniform':
            neighbors = knn(X_test)
            y_pred = np.array([np.argmax(np.bincount(y_train[neighbor])) for neighbor in neighbors])
             
            #y_train[neighbor]=[10001]
            #np.bincount[3,2]
        #np.argmax gives index as 0
            return y_pred 
    
    
        if weights=='distance':
        
            dist, neigh_ind = knn(X_test, return_distance=True)
        
            inv_dist = 1/dist
            
            mean_inv_dist = inv_dist / np.sum(inv_dist, axis=1)[:, np.newaxis]
            
            proba = []
            
            for i, row in enumerate(mean_inv_dist):
                
                row_pred = self.y_train[neigh_ind[i]]
                
                for k in range(class_num):
                    indices = np.where(row_pred==k)
                    prob_ind = np.sum(row[indices])
                    proba.append(np.array(prob_ind))
        
            predict_proba = np.array(proba).reshape(X_test.shape[0], class_num)
            
            y_pred = np.array([np.argmax(item) for item in predict_proba])
            
            return y_pred

In [3]:
import numpy as np


class KNearestNeighbors():
    def __init__(self, X_train, y_train, n_neighbors=5, weights='uniform'):

        self.X_train = X_train
        self.y_train = y_train

        self.n_neighbors = n_neighbors
        self.weights = weights

        self.n_classes = 3

    def euclidian_distance(self, a, b):
        return np.sqrt(np.sum((a - b)**2, axis=1))

    def kneighbors(self, X_test, return_distance=False):

        dist = []
        neigh_ind = []

        point_dist = [self.euclidian_distance(x_test, self.X_train) for x_test in X_test]

        for row in point_dist:
            enum_neigh = enumerate(row)
            sorted_neigh = sorted(enum_neigh,
                                  key=lambda x: x[1])[:self.n_neighbors]

            ind_list = [tup[0] for tup in sorted_neigh]
            dist_list = [tup[1] for tup in sorted_neigh]

            dist.append(dist_list)
            neigh_ind.append(ind_list)

        if return_distance:
            return np.array(dist), np.array(neigh_ind)

        return np.array(neigh_ind)

    def predict(self, X_test):

        if self.weights == 'uniform':
            neighbors = self.kneighbors(X_test)
            y_pred = np.array([
                np.argmax(np.bincount(self.y_train[neighbor]))
                for neighbor in neighbors
            ])

            return y_pred

        if self.weights == 'distance':

            dist, neigh_ind = self.kneighbors(X_test, return_distance=True)

            inv_dist = 1 / dist

            mean_inv_dist = inv_dist / np.sum(inv_dist, axis=1)[:, np.newaxis]

            proba = []

            for i, row in enumerate(mean_inv_dist):

                row_pred = self.y_train[neigh_ind[i]]

                for k in range(self.n_classes):
                    indices = np.where(row_pred == k)
                    prob_ind = np.sum(row[indices])
                    proba.append(np.array(prob_ind))

            predict_proba = np.array(proba).reshape(X_test.shape[0],
                                                    self.n_classes)

            y_pred = np.array([np.argmax(item) for item in predict_proba])

            return y_pred

    def score(self, X_test, y_test):
        y_pred = self.predict(X_test)

        return float(sum(y_pred == y_test)) / float(len(y_test))

In [5]:
from sklearn.datasets import load_iris
#from KNearestNeighbors import KNearestNeighbors
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd


dataset = load_iris()

X = dataset.data
y = dataset.target

mu = np.mean(X, 0)
sigma = np.std(X, 0)
X = (X - mu ) / sigma

X_train, X_test, y_train, y_test = train_test_split(\
                X, y, test_size=0.3, random_state=45)

our_classifier = KNearestNeighbors(X_train, y_train, n_neighbors=3)
sklearn_classifier = KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train)

our_accuracy = our_classifier.score(X_test, y_test)
sklearn_accuracy = sklearn_classifier.score(X_test, y_test)

pd.DataFrame([[our_accuracy, sklearn_accuracy]],
             ['Accuracy'],    
             ['Our Implementation', 'Sklearn\'s Implementation'])

Our Implementation  Sklearn's Implementation
Accuracy            0.955556                  0.955556